version: '3.9'

services:
  app:
    build: .
    container_name: boaz_billz
    ports:
      - "8050:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:2006@db:5432/billz_integrate

  db:
    image: postgres:15
    container_name: boaz_billz_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2006
      POSTGRES_DB: billz_integrate
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: fastapi_redis
    restart: always
    volumes:
      - redis_data:/data


volumes:
  redis:
  postgres_data:
